@isTest
public class DocusignSOAPApi2_Test {

    public static testmethod void DocusignSOAPApi2_test(){
        Test.setMock(WebServiceMock.class, new QE_DocusignCounterSignMock_Test());
        new DocusignSOAPApi2.RecipientCorrectionCorrectedCaptiveInfo();
        new DocusignSOAPApi2.RequestTemplateWithDocumentFields_element();
        new DocusignSOAPApi2.EventNotification();
        new DocusignSOAPApi2.AvailableFolders();
        new DocusignSOAPApi2.ArrayOfPublishConnectFailuresResult();
        new DocusignSOAPApi2.CreateEnvelopeResponse_element();
        new DocusignSOAPApi2.SendEnvelopeResponse_element();
        new DocusignSOAPApi2.IDCheckInformation();
        new DocusignSOAPApi2.Document();
        
        
        new DocusignSOAPApi2.RequestDocumentPDFsResponse_element();
        new DocusignSOAPApi2.RecipientEsign();
        new DocusignSOAPApi2.ArrayOfCompositeTemplate();
        new DocusignSOAPApi2.EnvelopeAuditEventsResponse_element();
        new DocusignSOAPApi2.RequestTemplateListWithDocumentFields_element();
        new DocusignSOAPApi2.PurgeDocumentStatus();
        new DocusignSOAPApi2.PDFOptions();
        new DocusignSOAPApi2.RequestPDFResponse_element();
        new DocusignSOAPApi2.CorrectionStatus();
        
        new DocusignSOAPApi2.ArrayOfCaptiveRecipient1();
        new DocusignSOAPApi2.ArrayOfFolder();
        new DocusignSOAPApi2.ArrayOfTab();
        new DocusignSOAPApi2.VoidEnvelopeStatus();
        new DocusignSOAPApi2.RequestRecipientToken_element();
        new DocusignSOAPApi2.BCCEmailAddress();
        new DocusignSOAPApi2.RequestPDFNoWaterMark_element();
        new DocusignSOAPApi2.FilteredEnvelopeStatusChanges();
        new DocusignSOAPApi2.GetAccountBrandsResponse_element();
        
        new DocusignSOAPApi2.EnvelopeEvent();
        new DocusignSOAPApi2.RequestPDFNoWaterMarkResponse_element();
        new DocusignSOAPApi2.DocumentPDF();
        new DocusignSOAPApi2.GetFolderListResponse_element();
        new DocusignSOAPApi2.AuthenticationStatus();
        new DocusignSOAPApi2.RecipientSMSAuthentication();
        new DocusignSOAPApi2.ArrayOfString1();
        new DocusignSOAPApi2.ArrayOfString2();
        new DocusignSOAPApi2.CreateEnvelopeFromTemplatesResponse_element();
        new DocusignSOAPApi2.ArrayOfString3();
        new DocusignSOAPApi2.ArrayOfString4();
        new DocusignSOAPApi2.PurgeDocuments_element();
        new DocusignSOAPApi2.ConnectFailuresFilter();
        new DocusignSOAPApi2.ArrayOfString5();
        new DocusignSOAPApi2.ArrayOfString6();
        new DocusignSOAPApi2.AccountSettingsList();
        new DocusignSOAPApi2.CaptiveRecipientResults();
        new DocusignSOAPApi2.RequestRecipientFaxTokenResponse_element();
        
        new DocusignSOAPApi2.ArrayOfPositiveInteger();
        new DocusignSOAPApi2.GetStatusInDocuSignConnectFormat_element();
        new DocusignSOAPApi2.EnvelopeInformation();
        new DocusignSOAPApi2.AddressInformation();
        new DocusignSOAPApi2.RequestTemplateList_element();
        new DocusignSOAPApi2.ArrayOfDocument();
        new DocusignSOAPApi2.EnvelopeStatusFilter();
        new DocusignSOAPApi2.ErrorDetails();
        new DocusignSOAPApi2.Envelope();
        new DocusignSOAPApi2.RequestStatusCodesResponse_element();
        new DocusignSOAPApi2.ArrayOfAttachment();
        new DocusignSOAPApi2.Notification();
        new DocusignSOAPApi2.ArrayOfRecipientCorrection();
        new DocusignSOAPApi2.SynchEnvelopeStatus();
        new DocusignSOAPApi2.SSN9InformationInput();
        new DocusignSOAPApi2.RecipientCorrectionStatus();
        new DocusignSOAPApi2.CaptiveRecipientResults();
        new DocusignSOAPApi2.SynchEnvelope_element();
        
        new DocusignSOAPApi2.PublishConnectFailuresFilter();
        new DocusignSOAPApi2.RequestPDFRecipientsView_element();
        new DocusignSOAPApi2.GetAccountBrands_element();
        new DocusignSOAPApi2.RequestStatusesWithDocumentFields_element();
        new DocusignSOAPApi2.RequestRecipientFaxPDFResponse_element();
        new DocusignSOAPApi2.ArrayOfMatchBox();
        new DocusignSOAPApi2.RequestStatusChangesResponse_element();
        new DocusignSOAPApi2.SSN9Information();
        new DocusignSOAPApi2.DocumentPDFs();
        new DocusignSOAPApi2.DeleteEnvelopes_element();
        new DocusignSOAPApi2.ArrayOfEnvelopeEvent();
        new DocusignSOAPApi2.CaptiveRecipient();
        new DocusignSOAPApi2.MatchBox();
        new DocusignSOAPApi2.DOBInformation();
        new DocusignSOAPApi2.DocumentStatus();
        new DocusignSOAPApi2.AccountMembershipFeaturesList();
        new DocusignSOAPApi2.AnchorTab();
        new DocusignSOAPApi2.EventResult();
        new DocusignSOAPApi2.FormDataXfdfField();
        new DocusignSOAPApi2.CreateAccountBrands_element();
        new DocusignSOAPApi2.GetStatusInDocuSignConnectFormatResponse_element();
        new DocusignSOAPApi2.AddressBookPhoneNumber();
        new DocusignSOAPApi2.PublishConnectFailures_element();
        new DocusignSOAPApi2.Expirations();
        new DocusignSOAPApi2.RequestStatuses_element();
        new DocusignSOAPApi2.RequestStatusCodes_element();
        new DocusignSOAPApi2.DeleteAccountBrandsResponse_element();
        new DocusignSOAPApi2.RemoveAddressBookItemsResponse_element();
        new DocusignSOAPApi2.GetAuthenticationTokenResponse_element();
        new DocusignSOAPApi2.ArrayOfBrandRequestItem();
        new DocusignSOAPApi2.Attachment();
        
        new DocusignSOAPApi2.SynchEnvelope_element();
        new DocusignSOAPApi2.GetRecipientListResponse_element();
        new DocusignSOAPApi2.RequestDocumentPDFsRecipientsView_element();
        new DocusignSOAPApi2.FoldersFilter();
        new DocusignSOAPApi2.EnvelopeTemplate();
        new DocusignSOAPApi2.SSN4Information();
        new DocusignSOAPApi2.BrandDefinitions();
        new DocusignSOAPApi2.MoveEnvelopes_element();
        new DocusignSOAPApi2.GetConnectFailures_element();
        new DocusignSOAPApi2.ArrayOfTemplateReference();
        new DocusignSOAPApi2.RecipientStatus();
        new DocusignSOAPApi2.CreateAccountBrandsResponse_element();
        new DocusignSOAPApi2.Ping_element();
        new DocusignSOAPApi2.RequestPDFWithCert_element();
        new DocusignSOAPApi2.FolderFilter();
        new DocusignSOAPApi2.ArrayOfRecipient1();
        new DocusignSOAPApi2.FormData();
        new DocusignSOAPApi2.DocuSignEnvelopeInformation();
        new DocusignSOAPApi2.ArrayOfAddressBookRemoveItem();
        new DocusignSOAPApi2.RequestCorrectToken_element();
        new DocusignSOAPApi2.RequestCorrectTokenResponse_element();
        new DocusignSOAPApi2.TransferEnvelopeStatus();
        new DocusignSOAPApi2.PurgeDocumentsAndMetaData_element();
        new DocusignSOAPApi2.RequestStatusExResponse_element();
        new DocusignSOAPApi2.DeleteCaptiveRecipientsSignaturesArg();
        new DocusignSOAPApi2.CreateEnvelopeFromTemplatesAndFormsResponse_element();
        new DocusignSOAPApi2.PublishConnectFailuresResponse_element();
        new DocusignSOAPApi2.GetSharedAccessResponse_element();
        new DocusignSOAPApi2.SendEnvelope_element();
        new DocusignSOAPApi2.SetSharedAccessResponse_element();
        new DocusignSOAPApi2.InlineTemplate();
        new DocusignSOAPApi2.AddressInformationInput();
        new DocusignSOAPApi2.RequestPDFRecipientsViewResponse_element();
        new DocusignSOAPApi2.DocumentField();
        new DocusignSOAPApi2.PingResponse_element();
        new DocusignSOAPApi2.DeleteEnvelopesResponse_element();
        new DocusignSOAPApi2.UserInfo();
        new DocusignSOAPApi2.BrandResultItem();
        new DocusignSOAPApi2.Correction();
        new DocusignSOAPApi2.RequestSenderToken_element();
        new DocusignSOAPApi2.CreateAndSendEnvelopeResponse_element();
        new DocusignSOAPApi2.RequestRecipientTokenAuthenticationAssertion();
        new DocusignSOAPApi2.GetConnectFailuresResponse_element();
        new DocusignSOAPApi2.RequestStatusesEx_element();
        new DocusignSOAPApi2.RequestStatusResponse_element();
        new DocusignSOAPApi2.EnvelopeTemplates();
        new DocusignSOAPApi2.RequestDocumentPDFsExResponse_element();
        new DocusignSOAPApi2.GetSharedAccessResult();
        new DocusignSOAPApi2.DeleteEnvelopesArg();
        new DocusignSOAPApi2.RequestTemplates_element();
        new DocusignSOAPApi2.TabStatus();
        new DocusignSOAPApi2.ArrayOfEnvelopeStatus();
        new DocusignSOAPApi2.ArrayOfRecipientEvent();
        new DocusignSOAPApi2.RequestTemplateListWithDocumentFieldsResponse_element();
        new DocusignSOAPApi2.AddressBookRemoveItem();
        new DocusignSOAPApi2.RequestEnvelopeWithDocumentFieldsResponse_element();
        new DocusignSOAPApi2.PurgeDocumentsAndMetaDataResponse_element();
        new DocusignSOAPApi2.UpdateAddressBookItemsResponse_element();
        new DocusignSOAPApi2.CompositeTemplate();
        new DocusignSOAPApi2.GetRecipientEsignList_element();
        new DocusignSOAPApi2.RequestDocumentPDFsEx_element();
        new DocusignSOAPApi2.AccountSetting();
        new DocusignSOAPApi2.PDFMetaDataTemplate();
        new DocusignSOAPApi2.RequestRecipientFaxPDF_element();
        new DocusignSOAPApi2.RequestRecipientFaxPDF_element();
        new DocusignSOAPApi2.ArrayOfString();
        new DocusignSOAPApi2.VaultingOptions();
        new DocusignSOAPApi2.RequestPDFsWithOptionsResponse_element();
        new DocusignSOAPApi2.RequestRecipientTokenClientURLs();
        new DocusignSOAPApi2.SharedItemRequest();
        new DocusignSOAPApi2.GetAccountSettingsListResponse_element();
        new DocusignSOAPApi2.SSN4InformationInput();
        new DocusignSOAPApi2.ExportAuthoritativeCopyResponse_element();
        new DocusignSOAPApi2.FolderTypeInfo();
        new DocusignSOAPApi2.ConnectFailure();
        new DocusignSOAPApi2.ArrayOfBCCEmailAddress();
        new DocusignSOAPApi2.ArrayOfSAMLAttribute();
        new DocusignSOAPApi2.RecipientEvent();
        new DocusignSOAPApi2.ArrayOfCaptiveRecipient();
        new DocusignSOAPApi2.RequestTemplateWithDocumentFieldsResponse_element();
        new DocusignSOAPApi2.GetRecipientEsignListResponse_element();
        new DocusignSOAPApi2.GetAddressBookItemsResponse_element();
        new DocusignSOAPApi2.CreateEnvelope_element();
        new DocusignSOAPApi2.Reminders();
        new DocusignSOAPApi2.AcknowledgeAuthoritativeCopyExportResponse_element();
        new DocusignSOAPApi2.GetAuthenticationToken_element();
        new DocusignSOAPApi2.RequestEnvelope_element();
        new DocusignSOAPApi2.BrandDeleteRequest();
        new DocusignSOAPApi2.ExportAuthoritativeCopy_element();
        new DocusignSOAPApi2.ArrayOfCustomField();
        new DocusignSOAPApi2.RequestPDFWithOptionsResponse_element();
        new DocusignSOAPApi2.RequestStatusChanges_element();
        new DocusignSOAPApi2.ArrayOfEnvelopeStatusCode();
        new DocusignSOAPApi2.ArrayOfBrandResultItem();
        new DocusignSOAPApi2.EnvelopeSettings();
        new DocusignSOAPApi2.SaveTemplateResult();
        new DocusignSOAPApi2.UpdateAddressBookItems_element();
        new DocusignSOAPApi2.FilteredEnvelopeStatuses();
        new DocusignSOAPApi2.ArrayOfFormDataXfdfField();
        new DocusignSOAPApi2.RequestDocumentPDFs_element();
        new DocusignSOAPApi2.DeleteCaptiveRecipientsSignatures_element();
        new DocusignSOAPApi2.RecipientPhoneAuthentication();
        new DocusignSOAPApi2.TemplateReferenceFieldDataDataValue();
        new DocusignSOAPApi2.SharedAccessItemResult();
        new DocusignSOAPApi2.SaveTemplate_element();
        new DocusignSOAPApi2.RequestRecipientFaxToken_element();
        new DocusignSOAPApi2.RecipientEmailNotification();
        new DocusignSOAPApi2.ArrayOfRecipient();
        new DocusignSOAPApi2.CreateEnvelopeFromTemplatesAndForms_element();
        new DocusignSOAPApi2.GetAddressBookItems_element();
        new DocusignSOAPApi2.GetAccountMembershipFeaturesList_element();
        new DocusignSOAPApi2.TransferEnvelope_element();
        new DocusignSOAPApi2.PublishConnectFailuresResult();
        new DocusignSOAPApi2.EmailSettings();
        new DocusignSOAPApi2.ArrayOfInlineTemplate();
        new DocusignSOAPApi2.Folder();
        new DocusignSOAPApi2.EnvelopeStatusChange();
        new DocusignSOAPApi2.DeleteCaptiveRecipientsSignaturesResponse_element();
        new DocusignSOAPApi2.SetSharedAccess_element();
        new DocusignSOAPApi2.RequestStatusWithDocumentFieldsResponse_element();
        new DocusignSOAPApi2.GetAccountSettingsList_element();
        new DocusignSOAPApi2.ServerTemplate();
        new DocusignSOAPApi2.RequestRecipientTokenResponse_element();
        new DocusignSOAPApi2.UpdateAddressBookResult();
        new DocusignSOAPApi2.RequestPDFWithOptions_element();
        new DocusignSOAPApi2.RequestPDFWithCertResponse_element();
        new DocusignSOAPApi2.IDCheckInformationInput();
        new DocusignSOAPApi2.SetSharedAccessRequest();
        new DocusignSOAPApi2.SetSharedAccessResult();
        new DocusignSOAPApi2.RequestStatusesExResponse_element();
        new DocusignSOAPApi2.EnvelopeStatusChangeFilter();
        new DocusignSOAPApi2.EnvelopeStatus();
        new DocusignSOAPApi2.FolderResults();
        new DocusignSOAPApi2.UploadTemplateResponse_element();
        new DocusignSOAPApi2.Tab();
        new DocusignSOAPApi2.RequestPDFsWithOptions_element();
        new DocusignSOAPApi2.RequestDocumentPDFsRecipientsViewResponse_element();
        new DocusignSOAPApi2.TransferEnvelopeResponse_element();
        new DocusignSOAPApi2.ArrayOfConnectFailure();
        new DocusignSOAPApi2.AddressBookItem();
        new DocusignSOAPApi2.RecipientStatusEsignAgreementInformation();
        new DocusignSOAPApi2.CreateAndSendEnvelope_element();
        new DocusignSOAPApi2.ArrayOfEnvelopeStatusChange();
        new DocusignSOAPApi2.ArrayOfServerTemplate();
        new DocusignSOAPApi2.ArrayOfDocumentField();
        new DocusignSOAPApi2.RequestCertificate_element();
        new DocusignSOAPApi2.ArrayOfTemplateReferenceFieldDataDataValue();
        new DocusignSOAPApi2.RequestStatusesResponse_element();
        new DocusignSOAPApi2.RequestTemplateListResponse_element();
        new DocusignSOAPApi2.ArrayOfTemplateReferenceRoleAssignment();
        new DocusignSOAPApi2.EnvelopeAuditEventsResult_element();
        new DocusignSOAPApi2.CorrectAndResendEnvelope_element();
        new DocusignSOAPApi2.ArrayOfFolderItem();
        new DocusignSOAPApi2.GetAccountMembershipFeaturesListResponse_element();
        new DocusignSOAPApi2.GetAccountMembershipFeaturesListResponse_element();
        new DocusignSOAPApi2.SharedUserInfoResult();
        new DocusignSOAPApi2.EnvelopePDF();
        new DocusignSOAPApi2.RequestTemplate_element();
        new DocusignSOAPApi2.AuthoritativeCopyExportStatus();
        new DocusignSOAPApi2.GetFolderList_element();
        new DocusignSOAPApi2.RequestPDF_element();
        new DocusignSOAPApi2.BrandRequestItem();
        new DocusignSOAPApi2.RequestStatusEx_element();
        new DocusignSOAPApi2.ArrayOfDocumentPDF();
        new DocusignSOAPApi2.SharedUserInfoRequest();
        
        new DocusignSOAPApi2.SharedUserInfoRequest();
        new DocusignSOAPApi2.Recipient();
        new DocusignSOAPApi2.FormDataXfdf();
        new DocusignSOAPApi2.RecipientCaptiveInfo();
        new DocusignSOAPApi2.ArrayOfRecipientStatus();
        new DocusignSOAPApi2.FolderItem();
        new DocusignSOAPApi2.SharedItemResult();
        new DocusignSOAPApi2.ArrayOfDocumentStatus();
        new DocusignSOAPApi2.GetFolderItems_element();
        new DocusignSOAPApi2.ArrayOfAddressBookItem();
        new DocusignSOAPApi2.RequestSenderTokenResponse_element();
        new DocusignSOAPApi2.RequestCertificateResponse_element();
        new DocusignSOAPApi2.EnvelopeStatusFilterBeginDateTime();
        new DocusignSOAPApi2.RecipientSignatureInfo();
        new DocusignSOAPApi2.PurgeDocumentsResponse_element();
        new DocusignSOAPApi2.DeleteAccountBrands_element();
        new DocusignSOAPApi2.VoidEnvelope_element();
        new DocusignSOAPApi2.SaveTemplateResponse_element();
        new DocusignSOAPApi2.ArrayOfTabStatus();
        new DocusignSOAPApi2.SAMLAttribute();
        new DocusignSOAPApi2.DOBInformationInput();
        new DocusignSOAPApi2.GetFolderItemsResponse_element();
        new DocusignSOAPApi2.TemplateReferenceRoleAssignment();
        new DocusignSOAPApi2.RecipientList();
        new DocusignSOAPApi2.ArrayOfRecipientCorrectionStatus();
        new DocusignSOAPApi2.SharedAccessFilter();
        new DocusignSOAPApi2.RecipientCorrection();
        new DocusignSOAPApi2.CorrectAndResendEnvelopeResponse_element();
        new DocusignSOAPApi2.VoidEnvelopeResponse_element();
        new DocusignSOAPApi2.EnvelopeAuditEvents_element();
        new DocusignSOAPApi2.RequestEnvelopeWithDocumentFields_element();
        new DocusignSOAPApi2.EnvelopeTemplateDefinition();
        new DocusignSOAPApi2.ArrayOfAddressBookItem1();
        new DocusignSOAPApi2.RequestEnvelopeResponse_element();
        new DocusignSOAPApi2.RequestStatusesWithDocumentFieldsResponse_element();
        new DocusignSOAPApi2.ArrayOfEnvelopeTemplate();
        new DocusignSOAPApi2.SharedItems();
        new DocusignSOAPApi2.MoveEnvelopesArg();
        new DocusignSOAPApi2.UploadTemplate_element();
        new DocusignSOAPApi2.RemoveAddressBookItems_element();
        new DocusignSOAPApi2.PDFsOptions();
        new DocusignSOAPApi2.RecipientEsignList();
        new DocusignSOAPApi2.TemplateReferenceFieldData();
        new DocusignSOAPApi2.AcknowledgeAuthoritativeCopyExport_element();
        new DocusignSOAPApi2.TemplateReference();
        new DocusignSOAPApi2.RecipientSAMLAuthentication();
        new DocusignSOAPApi2.GetSharedAccess_element();
        new DocusignSOAPApi2.ArrayOfRecipientEsign();
        new DocusignSOAPApi2.BrandResults();
        new DocusignSOAPApi2.RequestTemplatesResponse_element();
        new DocusignSOAPApi2.VaultingDetails();
        new DocusignSOAPApi2.GetRecipientList_element();
        new DocusignSOAPApi2.CustomField();
        new DocusignSOAPApi2.RequestStatusWithDocumentFields_element();
        new DocusignSOAPApi2.AuthoritativeCopyExportDocuments();
        new DocusignSOAPApi2.MoveEnvelopesResponse_element();
        new DocusignSOAPApi2.RequestTemplateResponse_element();
        new DocusignSOAPApi2.SynchEnvelopeResponse_element();
        new DocusignSOAPApi2.CreateEnvelopeFromTemplates_element();
        new DocusignSOAPApi2.RequestStatus_element();
        DocusignSOAPApi2.APIServiceSoap soap=new DocusignSOAPApi2.APIServiceSoap();
        try{
        soap.RequestDocumentPDFsRecipientsView('envelopeID', 'name', 'email@email.com');
        }catch(exception e){
        }

        try{
        soap.RequestTemplate('RequestTemplate', false);
        }catch(exception e){
        }

        try{
        soap.PurgeDocuments('envelopeID');
        }catch(exception e){
        }

        try{
        soap.RequestStatusWithDocumentFields('envelopeID');
        }catch(exception e){
        }

        try{
        soap.RequestEnvelope('envelopeID', true);
        }catch(exception e){
        }
        try{
        soap.RequestPDFWithCert('envelopeID', true);
        }catch(exception e){
        }

        try{
        soap.RequestPDF('envelopeID');
        }catch(exception e){
        }

        try{
        soap.UploadTemplate('envelopeID', 'name', true);
        }catch(exception e){
        }
        
        try{
        soap.RequestCorrectToken('envelopeID', true, 'string');
        }catch(exception e){
        }
        try{
        soap.GetAccountSettingsList('envelopeID');
        }catch(exception e){
        }
        try{
        soap.TransferEnvelope('envelopeID', 'name', 'idd');
        }catch(exception e){
        }
        try{
        soap.RequestStatus('envelopeID');
        }catch(exception e){
        }
        
        try{
        soap.PurgeDocumentsAndMetaData('envelopeID');
        }catch(exception e){
        }
        
        try{
        soap.GetAccountBrands('envelopeID');
        }catch(exception e){
        }
        try{
        soap.GetAuthenticationToken('envelopeID');
        }catch(exception e){
        }
        try{
        soap.RequestTemplateWithDocumentFields('envelopeID', false);
        }catch(exception e){
        }
        try{
        soap.VoidEnvelope('envelopeID','reason');
        }catch(exception e){
        }
        
        try{
        soap.GetAccountMembershipFeaturesList('envelopeID');
        }catch(exception e){
        }
        
        
        
        
        try{
        soap.GetRecipientList('envelopeID', 'str');
        }catch(exception e){
        }
        try{
        soap.RequestEnvelopeWithDocumentFields('envelopeID', false);
        }catch(exception e){
        }
        try{
        soap.SendEnvelope('envelopeID','reason');
        }catch(exception e){
        }
        
        try{
        soap.RequestDocumentPDFsEx('envelopeID');
        }catch(exception e){
        }
        try{
        soap.SynchEnvelope('envelopeID','reason', false);
        }catch(exception e){
        }
        
        
        try{
        soap.RequestDocumentPDFs('envelopeID');
        }catch(exception e){
        }
        try{
        soap.ExportAuthoritativeCopy('envelopeID');
        }catch(exception e){
        }
        try{
        soap.EnvelopeAuditEvents('envelopeID');
        }catch(exception e){
        }
        
        try{
        soap.RequestDocumentPDFsEx('envelopeID');
        }catch(exception e){
        }
        try{
        soap.RequestPDFNoWaterMark('envelopeID');
        }catch(exception e){
        }
        
        try{
        soap.RequestStatusEx('envelopeID');
        }catch(exception e){
        }
        
    }
}