//@isTest
public class OnlineSalesHelperTest {
   /* @TestSetup static void makeData(){
        TestDataFactory.createTriggerSettingsEntry();
        TestDataFactory.createSFDCIntacctMapping();
    }
    @isTest static void test1(){
        OnlineSalesHelper.insertedProductMap = new Map<Id,Product2>();
        OnlineSalesHelper.findLead('test@test.com');
        //OnlineSalesHelper.getAccount(, true);
    }*/    

}