/**
 * @File Name          : QEIntacctCalloutBatchTest.cls
 * @Description        : 
 * @Author             : jagrawal@addonblue.com
 * @Group              : 
 * @Last Modified By   : Lovel Panchal
 * @Last Modified On   : 5/11/2020, 9:36:50 AM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    5/11/2020   jagrawal@addonblue.com     Initial Version
**/
@isTest
public class QEIntacctCalloutBatchTest{

    public static testMethod void testmethod1234(){
    //     String Accrecid = Schema.SobjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
    //     Account acc = new Account();
    //     acc.RecordTypeId  = Accrecid;
    //     acc.Name = 'testName';
    //     acc.From_Lead_Convert__c = true;
    //     acc.Record_Id__c = 'Sales Order-SO0050';
    //     insert acc;
        
    //     Contact contact = new Contact();
    //     contact.accountid = acc.id;
    //     contact.lastname='test'; 
    //     contact.email='test@test.com';
    //     contact.Primary_Contact__c  = true;
    //     contact.Record_Id__c = 'Sales Order-SO0050';
    //     insert contact;
        
    //     QE360_Event__c   evt = new QE360_Event__c();
    //     evt.Name = 'test event';
    //     evt.Start_Date__c = Date.Parse('8/21/2015');
    //     evt.End_Date__c = Date.Parse('8/24/2015');
    //     insert evt;
        
        
        
    //     String oppRecid = Schema.SobjectType.Opportunity.getRecordTypeInfosByName().get('Business Opportunity').getRecordTypeId();
    //     Opportunity opp = new Opportunity();
    //     opp.RecordTypeId = oppRecid;
    //     opp.accountid = acc.id;
    //     opp.Name = 'test opportunity';
    //     opp.StageName = 'Qualified';
    //     opp.Payment_Method__c = 'Check';
    //     opp.Event__c = evt.id;
    //     opp.CloseDate = date.parse('12/27/2017');
    //     opp.Contact_Site__c = 'barrettjacksonvip.com';
    //     opp.Record_Id__c  = 'Sales Order-SO0050';
    //     opp.Primary_Contact__c = contact.Id;
    //     opp.OwnerId  = u.Id;
    //     insert opp;

    //     QEIntacctCalloutBatch objCtrl = new QEIntacctCalloutBatch(new List<String>());
    //     DataBase.executeBatch(objCtrl);
    //     QEIntacctCalloutBatch.sendDataIntacct(opp.Id);
    //     QEIntacctCalloutBatch.genDynQuery('', null, null, null);
    }
}